In [16]:
pip install tensorflow

In [17]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [18]:
a = tf.constant(5)
print(a)
v = tf.constant([1,2,3,4])
print(v)
m = tf.constant([[1,2],[3,4]])
print(m)
t3 = tf.constant([[1,2],[3,4],[5,6],[6,7]])
print(t3)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [6 7]], shape=(4, 2), dtype=int32)


In [19]:
a=tf.constant(24)
b=tf.constant(26)
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))
print(tf.pow(a,b))

tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(-2, shape=(), dtype=int32)
tf.Tensor(624, shape=(), dtype=int32)
tf.Tensor(0.9230769230769231, shape=(), dtype=float64)
tf.Tensor(0, shape=(), dtype=int32)


In [20]:

a=tf.constant([10,20,30])
b=tf.constant([34,2,7])
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))

tf.Tensor([44 22 37], shape=(3,), dtype=int32)
tf.Tensor([-24  18  23], shape=(3,), dtype=int32)
tf.Tensor([340  40 210], shape=(3,), dtype=int32)
tf.Tensor([ 0.29411765 10.          4.28571429], shape=(3,), dtype=float64)


In [21]:
a= tf.constant([10,20,30])
print(a.dtype,a.shape,tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)
